import tensorflow as tf


MAX_CPUS = 16
DATA_TYPE = tf.float32
MATMUL_BATCHES_KW = 4
MATMUL_BATCHES_TD = 4
PREDICT_BATCHES = 5
TRAPDOOR_BATCHES = 4
CLUSTERING_BATCHES = 8

NUM_GPUS = 1

PROFILE_MATMUL = False

PROFILE_PREDICTION_REFINED = False
PROFILE_PREDICTION_K = False

PROFILE_STRATEGY = False
